name: personal_trainer_app
description: "A new Flutter project."

version: 1.0.1+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  get_it: ^8.0.3
  flutter_bloc: ^9.0.0
  rxdart: ^0.28.0

  flutter_launcher_icons: ^0.14.3

  wakelock_plus: ^1.2.10
  vibration: ^3.1.3
  share_plus: ^10.1.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

